### ISSUE TITLE
k9s feature is failing with 0.27.0/latest

### ISSUE THREAD

**Issue by rjfmachado** [dhoeric/features#13]
Looks like they switched from x86_64 to amd64 in the filename :)

architecture="$(uname -m)"
case $architecture in
    x86_64) architecture="x86_64";;
    aarch64 | armv8* | arm64) architecture="arm64";;
    *) echo "(!) Architecture $architecture unsupported"; exit 1 ;;
esac

new release is [k9s_Linux_amd64.tar.gz](https://github.com/derailed/k9s/releases/download/v0.27.0/k9s_Linux_amd64.tar.gz)
old release is [k9s_Linux_x86_64.tar.gz](https://github.com/derailed/k9s/releases/download/v0.26.7/k9s_Linux_x86_64.tar.gz)

**Comment by boez-za** [comment]
Hello,

Any update on when this might be merged?


Thank you!
